language: python

# command to install dependencies
install:
    - pip install --upgrade -r requirements.txt --use-mirrors
    - pip install -e 'git+https://github.com/okfn/ckan.git@ckan-1.8#egg=ckan' --use-mirrors
    - wget https://raw.github.com/okfn/ckan/ckan-1.8/pip-requirements.txt -O ckan-requirements.txt
    - pip install -r ckan-requirements.txt

# command to run tests
script: nosetests
